# Generated by Django 4.0.3 on 2022-12-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='messageactionitem',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='messagecategory',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='room',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='shopmanagement',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shopmanagement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shopmessage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shopmessage',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shopmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shopmessageaction',
            name='action',
        ),
        migrations.RemoveField(
            model_name='shopmessageaction',
            name='message',
        ),
        migrations.RemoveField(
            model_name='shopmessageaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MessageActionItem',
        ),
        migrations.DeleteModel(
            name='MessageCategory',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.DeleteModel(
            name='ShopManagement',
        ),
        migrations.DeleteModel(
            name='ShopMessage',
        ),
        migrations.DeleteModel(
            name='ShopMessageAction',
        ),
    ]
